// CineWatch — 4K Ultra HD Movies & Series Data
// Edit this file to add, remove, or edit 4K titles.
// Set is4k: true on every entry.

window._FOURK_DATA = [
  {
    title: "Spider-Man: Brand New Day",
    type: "Movie",
    year: 2026,
    rating: 8.1,
    age: "PG-13",
    duration: "2h 25m",
    genres: ["Action", "Adventure", "Sci-Fi"],
    poster: "https://www.themoviedb.org/t/p/w600_and_h900_face/bjiS5ipwxb9JFy3XRRN4OAilSeX.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/7iwUUcKURMT7aKfCwMy6YnGtchD.jpg",
    videoUrl: "E:/spider-manbnd.mkv",
    trailerUrl: "https://www.youtube.com/watch?v=daXaTug8rL4",
    overview: "Peter Parker fights crime full-time as Spider-Man in a world that no longer remembers him. The pressure of watching old friends move on without him sparks changes he is not sure he can control. This transformation might be the only thing that can stop a shocking new threat to the city — a powerful villain no one can even see.",
    overviewKurdish: "پیتەر پارکەر بە تەواوی کاتی خۆی وەک سپایدەرمان تەرخان دەکات، لە جیهانێکدا کە چیتر ئەو ناناسێتەوە. گوشاری بینینی هاوڕێیەکی کۆن کە بێ ئەو بەردەوامە لە ژیانیدا، دەبێتە هۆی گۆڕانێک کە دڵنیا نییە بتوانێت بەڕێوەی ببات.",
    director: "Destin Daniel Cretton",
    cast: ["Tom Holland", "Zendaya", "Sadie Sink", "Jacob Batalon", "Jon Bernthal", "Tramell Tillman", "Michael Mando", "Mark Ruffalo"],
    trending: true,
    featured: true,
    is4k: true,
    seasons: []
  },
  {
    title: "Spider-Man: No Way Home",
    type: "Movie",
    year: 2021,
    rating: 8.2,
    age: "PG-13",
    duration: "2h 28m",
    genres: ["Action", "Adventure", "Sci-Fi"],
    poster: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    trailerUrl: "https://www.youtube.com/watch?v=JfVOs4VSpmA",
    overview: "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous.",
    director: "Jon Watts",
    cast: ["Tom Holland", "Zendaya", "Benedict Cumberbatch", "Jacob Batalon", "Willem Dafoe"],
    trending: true,
    is4k: true,
    seasons: []
  },
  {
    title: "Dune: Part Two",
    type: "Movie",
    year: 2024,
    rating: 8.6,
    age: "PG-13",
    duration: "2h 46m",
    genres: ["Action", "Adventure", "Sci-Fi"],
    poster: "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s520QIq.jpg",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    trailerUrl: "https://www.youtube.com/watch?v=Way9Dexny3w",
    overview: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
    director: "Denis Villeneuve",
    cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson", "Javier Bardem", "Austin Butler"],
    trending: true,
    is4k: true,
    seasons: []
  },
  {
    title: "Oppenheimer",
    type: "Movie",
    year: 2023,
    rating: 8.9,
    age: "R",
    duration: "3h 00m",
    genres: ["Biography", "Drama", "History"],
    poster: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    trailerUrl: "https://www.youtube.com/watch?v=uYPbbksJxIg",
    overview: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
    director: "Christopher Nolan",
    cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr."],
    is4k: true,
    seasons: []
  },
  {
    title: "The Batman",
    type: "Movie",
    year: 2022,
    rating: 7.9,
    age: "PG-13",
    duration: "2h 56m",
    genres: ["Action", "Crime", "Drama"],
    poster: "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/5P8SmMzSNYikXpxil6BYz9G660E.jpg",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    trailerUrl: "https://www.youtube.com/watch?v=mqqft2x_Aa4",
    overview: "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption.",
    director: "Matt Reeves",
    cast: ["Robert Pattinson", "Zoë Kravitz", "Paul Dano", "Jeffrey Wright", "Colin Farrell"],
    is4k: true,
    seasons: []
  },
  {
    title: "Avatar: The Way of Water",
    type: "Movie",
    year: 2022,
    rating: 7.6,
    age: "PG-13",
    duration: "3h 12m",
    genres: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
    poster: "https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    trailerUrl: "https://www.youtube.com/watch?v=d9MyW72ELq0",
    overview: "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na'vi race to protect their home.",
    director: "James Cameron",
    cast: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver", "Stephen Lang"],
    is4k: true,
    seasons: []
  },
  {
    title: "Top Gun: Maverick",
    type: "Movie",
    year: 2022,
    rating: 8.3,
    age: "PG-13",
    duration: "2h 10m",
    genres: ["Action", "Drama"],
    poster: "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/odJ42qqTeFiCoagSC5xyh20cy65.jpg",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4",
    trailerUrl: "https://www.youtube.com/watch?v=qSqVVhua5s4",
    overview: "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN's elite graduates on an impossible mission.",
    director: "Joseph Kosinski",
    cast: ["Tom Cruise", "Miles Teller", "Jennifer Connelly", "Jon Hamm"],
    is4k: true,
    seasons: []
  },
  {
    title: "Interstellar",
    type: "Movie",
    year: 2014,
    rating: 8.7,
    age: "PG-13",
    duration: "2h 49m",
    genres: ["Adventure", "Drama", "Sci-Fi"],
    poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    trailerUrl: "https://www.youtube.com/watch?v=zSWdZVtXT7E",
    overview: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
    director: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"],
    is4k: true,
    seasons: []
  }
];
